### ISSUE TITLE
Access violation in tdelibs-9999

### ISSUE THREAD

**Issue by ethus3h** [Fat-Zer/trinity#9] opened 2016-09-27 14:16 UTC
```
[100%] Built target tdetexteditor_kdatatool-module
creating test infrastructure
[100%] Built target testing
[100%] Built target tdetexteditor_docwordcompletion-module
[100%] Built target libkatepart-module
performing tests on vcardparser
 * ACCESS DENIED:  mkdir:        /root/.trinity
 * ACCESS DENIED:  mkdir:        /root/.trinity
 * ACCESS DENIED:  mkdir:        /root/.trinity
 * ACCESS DENIED:  mkdir:        /root/.trinity
 * ACCESS DENIED:  mkdir:        /root/.trinity
 * ACCESS DENIED:  mkdir:        /root/.trinity
Checking: ./tests/vcard1.vcf   OK
Checking: ./tests/vcard2.vcf   OK
Checking: ./tests/vcard3.vcf   OK
Checking: ./tests/vcard4.vcf   OK
Checking: ./tests/vcard6.vcf   OK
Checking: ./tests/vcard7.vcf   OK
Checking: ./tests/vcard8.vcf   OK
Checking: ./tests/vcard9.vcf   OK
[100%] Built target test
Install the project...
```

(snip)

```
 * Installing documentation: tdeabc.plugins.evolution.README
 * Installing documentation: kate.NEWS
 * Installing documentation: tdeio.kssl.kssl.HOWTO
 * Installing documentation: tdeio.kssl.TODO
 * Installing documentation: arts.knotify.README
>>> Completed installing tdelibs-9999 into /var/tmp/portage/trinity-base/tdelibs-9999/image/

 * Final size of build directory: 309025 KiB
 * Final size of installed tree: 79049 KiB

 * --------------------------- ACCESS VIOLATION SUMMARY ---------------------------
 * LOG FILE: "/var/log/sandbox/sandbox-16017.log"
 * 
VERSION 1.0
FORMAT: F - Function called
FORMAT: S - Access Status
FORMAT: P - Path as passed to function
FORMAT: A - Absolute Path (not canonical)
FORMAT: R - Canonical Path
FORMAT: C - Command Line

F: mkdir
S: deny
P: /root/.trinity
A: /root/.trinity
R: /root/.trinity
C: /usr/trinity/14/bin/lnusertemp tmp 

F: mkdir
S: deny
P: /root/.trinity
A: /root/.trinity
R: /root/.trinity
C: /usr/trinity/14/bin/lnusertemp tmp 

F: mkdir
S: deny
P: /root/.trinity
A: /root/.trinity
R: /root/.trinity
C: /usr/trinity/14/bin/lnusertemp socket 

F: mkdir
S: deny
P: /root/.trinity
A: /root/.trinity
R: /root/.trinity
C: /usr/trinity/14/bin/lnusertemp socket 

F: mkdir
S: deny
P: /root/.trinity
A: /root/.trinity
R: /root/.trinity
C: /usr/trinity/14/bin/lnusertemp cache 

F: mkdir
S: deny
P: /root/.trinity
A: /root/.trinity
R: /root/.trinity
C: /usr/trinity/14/bin/lnusertemp cache 
 * --------------------------------------------------------------------------------

>>> Failed to emerge trinity-base/tdelibs-9999, Log file:

>>>  '/var/tmp/portage/trinity-base/tdelibs-9999/temp/build.log'

 * GNU info directory index is up-to-date.
elliot ~ # 
```

**Comment by ethus3h** [comment] 2016-10-25 17:56
This can be fixed by adding

```
    addpredict /root/.trinity
```

right before

```
trinity-base_src_install
```

.

**Comment by Fat-Zer** [comment] 2016-12-21 00:25
Sorry I haven't responded for a while.

The issue is result of combination of 2 conditions of wrong behaviour:
1. automated tests which are recently was added run unconditionally during make phase
2. lnusertemp doesn't respect HOME for root some why.

The first one is a larger one and requires some thinking/discussion/patches.
The second one can be tracked here: https://bugs.trinitydesktop.org/attachment.cgi?bugid=2739

I don't like to tweak the sandbox settings and taint the ebuild with addpredict.
As for now I suggest to remove _/usr/trinity/14/bin/lnusertemp_ before emerging the tdelibs.

The same will likely be required after the (2) will be fixed.

**Comment by Fat-Zer** [comment] 2017-01-05 03:56
Should be fine now. Remember to remove  /usr/trinity/14/bin/lnusertemp if it doesn't compiles...

**Closed as completed by Fat-Zer** 2017-01-05 03:56 UTC
Labels: bug, upstream
